import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useRef, useEffect } from "react";
import { gsap } from "gsap";
import Nav from "../components/Nav";

export default function Home() {
  const title = useRef();
  const button = useRef();

  // wait until DOM has been rendered
  useEffect(() => {
    gsap.to(title.current, { rotation: "+=360", opacity: 1, duration: 1.5 });
    gsap.to(button.current, { delay: 0.5, opacity: 1, duration: 1 });
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className={styles.main}>
        <section className={styles.hero} id="home">
          <h1 className={styles.title} ref={title}>
            Heckie & Huntie<span>Break The Internet</span>
          </h1>
          <button
            className={styles.button}
            ref={button}
            type="button"
            aria-label="Listen to the latest podcast"
          >
            Listen Now
          </button>
        </section>
        <section className={styles.about} id="about">
          <h2 className={styles.title}>About The Show</h2>
          <p className={styles.desc}>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis
            non qui quaerat. Impedit recusandae dolor ducimus alias, id sed
            animi unde dolorem. Doloremque, neque consequuntur expedita ex
            corporis asperiores atque.
          </p>
          <hr />
          <div className={styles.hosts}>
            <article>
              <Image
                className={styles.profile}
                src="https://via.placeholder.com/300x500"
                alt="Hector Velez"
                height="500"
                width="300"
              />
              <h3 className={styles.title}>Hector Velez</h3>
            </article>
            <article>
              <Image
                className={styles.profile}
                src="https://via.placeholder.com/300x500"
                alt="Hector Velez"
                height="500"
                width="300"
              />
              <h3 className={styles.title}>Hunter Trammell</h3>
            </article>
          </div>
        </section>
        <section className={styles.archive} id="archive">
          <h2 className={styles.title}>Previous Episodes</h2>
        </section>
      </main>
    </div>
  );
}
